TRUNCATE TABLE T_CATEGORIE;

TRUNCATE TABLE T_ARTICLE;

INSERT INTO T_CATEGORIE (CAT_LIBELLE)
VALUES  ("Habits"),
        ("Meubles"),
        ("Jouets"),
        ("Autres");

INSERT INTO T_ARTICLE (ID_CATEGORIE, ART_NOM, ART_PRIX, ART_DESCRIPTION, ART_IMAGE, ART_DATE, ART_ETAT)
VALUES  (0, "Veste", 10.00, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum aliquet, ornare purus vel, laoreet ligula. Nulla ultrices, justo at ultrices faucibus, ex est vehicula lorem, sed faucibus leo dolor et tellus. Maecenas nec nulla eget augue dapibus ultricies quis dignissim felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus nibh ante, tempus eu felis sed, vehicula consectetur ligula. Duis quis bibendum lacus. Phasellus et egestas massa. Suspendisse potenti. Fusce rhoncus nulla dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at magna accumsan, vehicula neque ut, luctus nulla. Phasellus ac neque luctus tellus finibus varius sagittis sit amet est. Phasellus non pellentesque lectus, vitae dignissim nulla. Donec sit amet leo dictum, ultrices ipsum non, convallis nibh. Phasellus eu eros diam.", "veste.jpg", "2017-02-20", 0),
		(0, "Veste", 10.00, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum aliquet, ornare purus vel, laoreet ligula. Nulla ultrices, justo at ultrices faucibus, ex est vehicula lorem, sed faucibus leo dolor et tellus. Maecenas nec nulla eget augue dapibus ultricies quis dignissim felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus nibh ante, tempus eu felis sed, vehicula consectetur ligula. Duis quis bibendum lacus. Phasellus et egestas massa. Suspendisse potenti. Fusce rhoncus nulla dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at magna accumsan, vehicula neque ut, luctus nulla. Phasellus ac neque luctus tellus finibus varius sagittis sit amet est. Phasellus non pellentesque lectus, vitae dignissim nulla. Donec sit amet leo dictum, ultrices ipsum non, convallis nibh. Phasellus eu eros diam.", "veste.jpg", "2017-02-20", 0),
		(0, "Veste", 10.00, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum aliquet, ornare purus vel, laoreet ligula. Nulla ultrices, justo at ultrices faucibus, ex est vehicula lorem, sed faucibus leo dolor et tellus. Maecenas nec nulla eget augue dapibus ultricies quis dignissim felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus nibh ante, tempus eu felis sed, vehicula consectetur ligula. Duis quis bibendum lacus. Phasellus et egestas massa. Suspendisse potenti. Fusce rhoncus nulla dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at magna accumsan, vehicula neque ut, luctus nulla. Phasellus ac neque luctus tellus finibus varius sagittis sit amet est. Phasellus non pellentesque lectus, vitae dignissim nulla. Donec sit amet leo dictum, ultrices ipsum non, convallis nibh. Phasellus eu eros diam.", "veste.jpg", "2017-02-20", 0),
		(0, "Veste", 10.00, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac ipsum aliquet, ornare purus vel, laoreet ligula. Nulla ultrices, justo at ultrices faucibus, ex est vehicula lorem, sed faucibus leo dolor et tellus. Maecenas nec nulla eget augue dapibus ultricies quis dignissim felis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus nibh ante, tempus eu felis sed, vehicula consectetur ligula. Duis quis bibendum lacus. Phasellus et egestas massa. Suspendisse potenti. Fusce rhoncus nulla dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis at magna accumsan, vehicula neque ut, luctus nulla. Phasellus ac neque luctus tellus finibus varius sagittis sit amet est. Phasellus non pellentesque lectus, vitae dignissim nulla. Donec sit amet leo dictum, ultrices ipsum non, convallis nibh. Phasellus eu eros diam.", "veste.jpg", "2017-02-20", 0);
