CREATE TABLE IF NOT EXISTS T_CATEGORIE (
    ID_CATEGORIE INT NOT NULL AUTO_INCREMENT,
    CAT_LIBELLE CHAR(40),
    PRIMARY KEY (ID_CATEGORIE)
);

CREATE TABLE IF NOT EXISTS T_ARTICLE (
    ID_ARTICLE INT NOT NULL AUTO_INCREMENT,
    ID_CATEGORIE INT NOT NULL,
    ART_NOM CHAR(40),
    ART_PRIX FLOAT(8,2),
    ART_DESCRIPTION TEXT,
    ART_IMAGE CHAR(40),
    ART_DATE DATE,
    ART_ETAT BOOLEAN,
    PRIMARY KEY (ID_ARTICLE)
);

ALTER TABLE T_ARTICLE ADD CONSTRAINT IF NOT EXISTS FK_APPARTENIR FOREIGN KEY (ID_CATEGORIE)
    REFERENCES T_CATEGORIE (ID_CATEGORIE) ON DELETE RESTRICT ON UPDATE RESTRICT;
